### PR TITLE
Rename to Stake Maturity

### PR DESCRIPTION
**Pull request by ftheirs**

### CODE REVIEW

**Review by yhql — APPROVED** [review]

**Comment by xchapron-ledger** [comment]
Linked to [B2CA-990](https://ledgerhq.atlassian.net/browse/B2CA-990)

**Comment by xchapron-ledger** [comment]
Manually removed from `main` history, should have not been merged on `main` but on `develop`. Will be reopened.

**Comment by ftheirs** [comment]
Hi @xchapron-ledger! Check that this PR includes only the [renaming commit](https://github.com/LedgerHQ/app-icp/pull/12/commits/ea286668ffde25e82496ecc301f78943edf1c313) but in develop branch you already have merged candid features. It might be not so trivial to build a version from develop using the current state and that's why I set main branch instead

**Comment by xchapron-ledger** [comment]
Manually put back on `main` history now that it has been deployed from a temp branch, tested on P4, and now deployed on P1.

**Pull request merged**
