### PR TITLE
Support for Stax & More Candid transactions

### PR DESCRIPTION
**Pull request by ftheirs**
Add support for Stax device
Improve printing address, principal, subaccount, etc for Stax
Update SDK
Update Zemu test: include Stax and run tests in parallel

New features (all transactions for Candid NNS):
- Disburse
- Join Community Fund
- Add Hotkey
- Remove Hotkey
- Register Vote
- Follow
- Send ICP
- Stake Neuron

Other changes:
- Now ICRC1 addresses follow [this encoding](https://github.com/dfinity/ICRC-1/pull/98/files#diff-cf72e3d78c946edc91e3b8d499b8c7a7e894daaca1922e33b9ab7e40544e5030)
- ICRC1 Transfer: Change in text encoding

### CODE REVIEW

**Comment by xchapron-ledger** [comment]
@ftheirs Hey,
Github consider this branch as not up to date with LedgerHQ remote develop branch, any reason for that?

**Comment by carlosala** [comment]
@xchapron-ledger that's probably due to your merge commits, that we don't have them. It shouldn't be a problem at all

**Comment by xchapron-ledger** [comment]
@carlosala @ftheirs Ok in fact this is due to the merge of https://github.com/LedgerHQ/app-icp/pull/13 directly on LedgerHQ repo main without being merged on Zondax repo main.
Once merged back on develop in https://github.com/LedgerHQ/app-icp/pull/15 we got now an history difference between Zondax and LedgerHQ repos...

Anyway I managed to trigger the tests, and they are failing. Probably a missing Zxlib update. Can you do it?

**Comment by xchapron-ledger** [comment]
Linked to https://ledgerhq.atlassian.net/browse/B2CA-1391

**Pull request merged**
